### ISSUE TITLE
When you build the game, it has error

### ISSUE THREAD

**Issue by Pixellore** [FBast/ReflexityAI#1]
Assets\Plugins\xNodeUtilityAi\Utils\TagList\TagListHelper.cs(2,7): error CS0246: The type or namespace name 'XNodeEditor' could not be found (are you missing a using directive or an assembly reference?)

**Comment by FBast** [comment]
Hi, it seems that you are using an old version of Reflexity. I forgot to merge the current release (3.3.2) back into the master branch, it is fixed know. You can download the master branch, or the reflection-node branch (which is the same than the master) or the old static-node branch (without reflection data). Thx for your feedback.
