### ISSUE TITLE
data reader propery node

### ISSUE THREAD

**Issue by thomasboulanger** [FBast/ReflexityAI#3]
pas d iterateurs sauf sur les bonus 
![image](https://user-images.githubusercontent.com/60351261/144836620-458577d4-ef3c-4ab1-9e73-3b6b49b3e3fd.png)
![image](https://user-images.githubusercontent.com/60351261/144836643-561403ec-6e81-4af7-89f1-93c68272801b.png)

**Comment by enzobenedetti** [comment]
De mon côté, le waypoints identity s'affiche sur l'itérator, mais il n'a pas l'air de fonctionner

**Comment by FBast** [comment]
Problème réglé en vidant le cache des dataSelector lors d'une déconnexion d'un port, fix sur la branch
