### ISSUE TITLE
Ranks select seem to not working

### ISSUE THREAD

**Issue by enzobenedetti** [FBast/ReflexityAI#4]
Select how to choose ranks seem to not work correctly

Setting the ranks as "Min" for the best option, but still select the highest rank

**Screenshots**
![image](https://user-images.githubusercontent.com/60351213/145372926-30d5e4bb-9ae1-44d4-8f40-fbde6528cc6c.png)
![image](https://user-images.githubusercontent.com/60351213/145372977-882ce06c-0ceb-4548-bc7a-779b5f17faaa.png)

**Comment by FBast** [comment]
Fixed on the main branch

**Comment by FBast** [comment]
Min, Max and Avg are used to merge together multiple rank associated to a same action, on your screen their is only one rank assigned (the currentHp value).

Therefore, rank should only be connected to utility and not plugged directly to data
