### ISSUE TITLE
crazy slow

### ISSUE THREAD

**Issue by laurentopia** [FBast/ReflexityAI#5]
the cube benchmark struggles
I see from the profiler that the system course through the graph each time
i could push an optim commit if you think that can be greatly sped up
I didn't go too deep to identify the largest contributor, usually it's string compare and list/dictionarry work
what do you think it is?

**Comment by FBast** [comment]
Hi laurentopia, in a previous version I used async treatment and queuing stack to optimize reflexions, this way I could mitigate CPU overload with a larger time between each individual reflexion. I have rollback this update for multiple bug encounter, now GC Alloc is at his minimum value and optimization can only be reached (in my pov) with async optimization. I will take a day or two for a large optimization commit, but I can't find any time for now. This project is largely based on reflection so it can be a pain in the ass to optimize correctly. If you want to fork it and try an optimization commit feel free to do. I'm interested by your results.

**Comment by FBast** [comment]
In fact i also remember using node data cache to prevent fetching reflection data but i rollback it too =/

**Comment by FBast** [comment]
A large bug with QueueAI coroutine starting for every ai in the game (instead of one coroutine for all ai) were causing a huge drop in fps, now it's totally fine, you can use the benchmark to try it.

**Comment by laurentopia** [comment]
Well done.
Are all the cubes running full AI on each frame?

**Comment by FBast** [comment]
An AI will run full process when his turn come on the queue, this mean that the more AI you use, the more the time between each of his reflexion is long. This allow to use a lots of AI with no framerate drops.

**Comment by laurentopia** [comment]
A load balancer, this is nice. Can they be prioritized by proximity to the camera?
